#!/bin/sh

PIDFILE=/var/run/packagemanager.pid
LOGFILE=/var/log/packagemanager.log

case "$1" in
    start)
        if [ -f $PIDFILE ] && ps `cat $PIDFILE`; then
            echo 'Already Running'
            exit 1
        fi
        PID=`/opt/packagemanager/run.sh > /var/log/packagemanager.log 2>&1 & echo $!`
        if [ -z $PID ]; then
            echo 'Fail'
        else
            echo $PID > $PIDFILE
            echo 'OK'
        fi
        ;;
    stop)
        if [ -f $PIDFILE ]; then
            kill `cat $PIDFILE`
            rm -f $PIDFILE
            echo 'OK'
        else
            echo 'Not Running'
        fi
        ;;
    status)
        if [ -f $PIDFILE ] && ps `cat $PIDFILE`; then
            echo 'Running'
        else
            echo 'Not Running'
        fi
    *)
        echo "Usage: /etc/init.d/packagemanager {start|stop|status}"
        exit 1
        ;;
esac

exit 0
