#!/bin/sh
### BEGIN INIT INFO
# Provides: packagemanager
# Required-Start: $local_fs $network
# Required-Stop: $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: packagemanager
# Description: package manager server daemon
### END INIT INFO

PIDFILE=/var/run/packagemanager.pid
LOGFILE=/var/log/packagemanager.log

case "$1" in
    start)
        if [ -f $PIDFILE ] && ps `cat $PIDFILE` > /dev/null; then
            echo 'Already Running'
            exit 1
        fi
        PID=`/opt/packagemanager/run.sh > /var/log/packagemanager.log 2>&1 & echo $!`
        if [ -z $PID ]; then
            echo 'Fail'
        else
            echo $PID > $PIDFILE
            echo 'OK'
        fi
        ;;
    stop)
        if [ -f $PIDFILE ]; then
            kill `cat $PIDFILE`
            rm -f $PIDFILE
            echo 'OK'
        else
            echo 'Not Running'
        fi
        ;;
    status)
        if [ -f $PIDFILE ] && ps `cat $PIDFILE` > /dev/null; then
            echo 'Running'
        else
            echo 'Not Running'
        fi
        ;;
    *)
        echo "Usage: /etc/init.d/packagemanager {start|stop|status}"
        exit 1
        ;;
esac

exit 0
